### ISSUE TITLE
emulators not found

### ISSUE THREAD

**Issue by moknit** [amrsa1/Android-Emulator-image#14]
~/Android-Emulator-image$ sudo docker exec --privileged -it -e EMULATOR_TIMEOUT=300 androidContainer bash -c "./start_emu_headless.sh"
* daemon not running; starting now at tcp:5037
* daemon started successfully
linux-gnu: emulator @nexus -no-window -no-snapshot -noaudio -no-boot-anim -memory 2048 -accel off -camera-back none -gpu off
nohup: appending output to 'nohup.out'
==> Checking emulator booting up status 🧐
==> adb: no devices/emulators found, please wait ⠇

**Comment by dtfsd** [comment]
Same problem

**Comment by amrsa1** [comment]
What device you are using guys ?

**Comment by dtfsd** [comment]
Nexus. Just running command by command as described in README file. At leas in my case I'm running on Ubuntu 22.04 Docker host. 

Running `emulator @nexus -no-window -no-snapshot -noaudio -no-boot-anim -memory 2048 -accel off -camera-back none -verbose` from within the container just ends up hanging like this:
<img width="1537" alt="image" src="https://github.com/amrsa1/Android-Emulator-image/assets/141913021/64d9a772-3215-44d0-920a-e7e83c395a31">

On the right side in the screen shot you can see that ADB inside the container is not seeing emulator at all.

**Comment by dtfsd** [comment]
I get the same result even if I run it locally on my Apple M2

**Comment by moknit** [comment]
> ~/Android-Emulator-image$ sudo docker exec --privileged -it -e EMULATOR_TIMEOUT=300 androidContainer bash -c "./start_emu_headless.sh"
> 
> * daemon not running; starting now at tcp:5037
> * daemon started successfully
>   linux-gnu: emulator @nexus -no-window -no-snapshot -noaudio -no-boot-anim -memory 2048 -accel off -camera-back none -gpu off
>   nohup: appending output to 'nohup.out'
>   ==> Checking emulator booting up status 🧐
>   ==> adb: no devices/emulators found, please wait ⠇

The issue was with the Linux AWS instance i used. The Linux AWS Instance should be a metal instance which supports hardware accelerations.

**Comment by amrsa1** [comment]
> I get the same result even if I run it locally on my Apple M2

M2 doesnt support nested virtualization unfortunately

**Comment by dtfsd** [comment]
> > I get the same result even if I run it locally on my Apple M2
> 
> M2 doesnt support nested virtualization unfortunately

That's new, thanks! Should it be able to run on AWS non-metal if there's the `-accel off` flag?

**Comment by amrsa1** [comment]
> > > I get the same result even if I run it locally on my Apple M2
> > 
> > M2 doesnt support nested virtualization unfortunately
> 
> That's new, thanks! Should it be able to run on AWS non-metal if there's the `-accel off` flag?

Start with metal instance
