### ISSUE TITLE
System UI isn't responding

### ISSUE THREAD

**Issue by MohabMohie** [amrsa1/Android-Emulator-image#2]
I keep getting this pesky message when I run my docker-compose instance as-is without any customizations.
Any help?
![image](https://user-images.githubusercontent.com/19201898/215363176-380dcf10-9d07-4d54-a3a9-ebf3f5b877ea.png)
sometimes it changes to this
![image](https://user-images.githubusercontent.com/19201898/215366416-dfbfeb13-bb8d-46bd-93f6-fafeee3aa6d4.png)

**Comment by amrsa1** [comment]
@MohabMohie 

Is it happening with only this particular app ?
Does the app supported by android 13 ? 

Is it possible to send the APK for debugging ?

**Comment by amrsa1** [comment]
Closed due to inactivity
