### ISSUE TITLE
emulator can't recover from container restart

### ISSUE THREAD

**Issue by dorsegal** [amrsa1/Android-Emulator-image#20]
I am running using docker-compose.yaml and I have added `restart: unless-stopped` option so it will restart in case something happens.
When there is a crash for whatever reason container is being restarted but emulator can't start. it is just hangs till timeout
![image](https://github.com/amrsa1/Android-Emulator-image/assets/7013837/e9950a61-ae73-4fce-b4c8-431d76268d34)

my docker-compose:
<img width="419" alt="image" src="https://github.com/amrsa1/Android-Emulator-image/assets/7013837/6ed5c9b5-05b0-4336-9794-bf97851e7073">

**Comment by amrsa1** [comment]
But it looks like emulator didnt crash.
It was fully booted according to you screenshot and moved to next step which is launching appium

**Comment by dorsegal** [comment]
I was a simulating a crash right after appium was starting.

**Comment by amrsa1** [comment]
But it looks like emulator didnt crash.
It was fully booted according to you screenshot and moved to next step which is launching appium

Try to run the command manually and see the output

**Comment by dorsegal** [comment]
The way I simulated a crash:

1. docker exec -it android bash
2. apt update && apt install -y procps
3. ps aux 
4. kill -9 {emulator PID}

**Comment by amrsa1** [comment]
> The way I simulated a crash:
> 
> 1. docker exec -it android bash
> 2. apt update && apt install -y procps
> 3. ps aux 
> 4. kill -9 {emulator PID}
> 

Try aslo to kill the adb server, before starting the emulator after being crashed

**Comment by dorsegal** [comment]
I found the issue. After checking emulator logs I see this error: `Running multiple emulators with the same AVD is an experimental feature.`

https://stackoverflow.com/questions/55328499/emulator-emulator-error-running-multiple-emulators-with-the-same-avd-is-an-ex

the solution I did was adding this line to `start_emu_headless.sh`:
`rm ~/.android/avd/*.avd/*.lock`

**Comment by amrsa1** [comment]
> I found the issue. After checking emulator logs I see this error: `Running multiple emulators with the same AVD is an experimental feature.`
> 
> https://stackoverflow.com/questions/55328499/emulator-emulator-error-running-multiple-emulators-with-the-same-avd-is-an-ex
> 
> the solution I did was adding this line to `start_emu_headless.sh`:
> `rm ~/.android/avd/*.avd/*.lock`

Awesome Gald that you have solved it.

I think also killing adb server will eliminate the first one so you wont have problem running another with same name.
